import type { AgentEvent } from "../types";

export type ChatEventSurface = "timeline" | "hidden" | "dock" | "strip-approval";

export const CHAT_EVENT_POLICY = {
  started: "timeline",
  "text-delta": "timeline",
  "assistant-message": "hidden",
  "tool-started": "timeline",
  "tool-completed": "timeline",
  "permission-required": "dock",
  "step-started": "hidden",
  "step-finished": "hidden",
  "verification-started": "timeline",
  "verification-check-started": "hidden",
  "verification-check-completed": "hidden",
  "verification-completed": "timeline",
  completed: "timeline",
  error: "timeline",
  fallback: "hidden",
  cancelled: "timeline",
  "context-assembled": "hidden",
  "task-started": "hidden",
  "task-completed": "hidden",
  "skill-selected": "hidden",
  "skill-check": "hidden",
  "skill-loaded": "hidden",
  "design-gate": "timeline",
  "user-question": "timeline",
  "plan-written": "hidden",
  "plan-created": "timeline",
  "plan-todo-updated": "hidden",
  "plan-build-started": "hidden",
  "plan-completed": "hidden",
  "plan-mode": "hidden",
  "agent-mode": "timeline",
  "branch-created": "hidden",
  "merge-conflicts": "timeline",
  "subagent-task-started": "timeline",
  "subagent-task-completed": "timeline",
  "sdd-task-started": "timeline",
  "sdd-task-completed": "timeline",
  "permission-classifier": "hidden",
  compact_boundary: "hidden",
  "llm-started": "hidden",
  "finish-branch": "dock",
  "approval-resolved": "strip-approval",
  compacted: "hidden",
  "run-resumed": "hidden",
  "hook-denied": "timeline",
  "hook-warned": "hidden",
  "hook-fired": "hidden",
  "workflow-started": "timeline",
  "workflow-step": "timeline",
  "workflow-checkpoint": "hidden",
  "workflow-approval-required": "dock",
  "workflow-completed": "timeline",
  "recovery-checkpoint": "hidden",
  "recovery-available": "timeline",
  "recovery-dismissed": "hidden",
  "recovery-cleared": "hidden",
  "recovery-rolled-back": "hidden",
  "orchestration-started": "timeline",
  "agent-started": "timeline",
  "agent-completed": "timeline",
  "orchestration-completed": "timeline",
  "mcp-server-started": "hidden",
  "mcp-server-ready": "hidden",
  "mcp-server-error": "hidden",
  "mcp-server-disconnected": "hidden",
  "mcp-discovered": "hidden",
  "mcp-tool-started": "hidden",
  "mcp-tool-completed": "hidden",
  "change-set-created": "hidden",
  "file-change-detected": "hidden",
  "change-hunk-created": "hidden",
  "review-started": "hidden",
  "change-hunk-accepted": "hidden",
  "change-hunk-rejected": "hidden",
  "file-change-accepted": "hidden",
  "file-change-rejected": "hidden",
  "change-set-accepted": "hidden",
  "change-set-rejected": "hidden",
  "review-conflict-detected": "hidden",
  "review-decision-undone": "hidden",
  "review-completed": "timeline",
  "knowledge-reflect-started": "hidden",
  "knowledge-reflect-skipped": "timeline",
  "knowledge-reflect-completed": "timeline",
} as const satisfies Record<AgentEvent["type"], ChatEventSurface>;

export function chatEventSurface(type: AgentEvent["type"]): ChatEventSurface {
  return CHAT_EVENT_POLICY[type];
}

export function isChatHiddenEvent(type: AgentEvent["type"]) {
  const surface = CHAT_EVENT_POLICY[type];
  return surface === "hidden" || surface === "dock";
}
