mod agent;
mod commands;
mod database;
mod error;
mod filesystem;
mod github;
mod mcp;
mod process;
mod rag;
mod secrets;
mod state;
mod terminal;

use commands::{
    agent::agent_ping,
    database::{
        db_agent_runs_get, db_agent_runs_list, db_agent_runs_upsert, db_agents_list, db_agents_upsert, db_conversations_archive,
        db_conversations_get, db_conversations_list, db_conversations_upsert, db_export_application_data,
        db_github_account_get, db_global_settings_list, db_global_settings_set, db_import_application_data,
        db_memory_delete, db_memory_get, db_memory_search, db_memory_upsert, db_messages_list,
        db_messages_upsert, db_project_files_delete, db_project_files_list, db_project_files_upsert,
        db_project_github_delete, db_project_github_get, db_project_github_upsert, db_project_settings_list,
        db_project_settings_set, db_projects_delete, db_projects_get, db_projects_get_by_path, db_projects_list,
        db_projects_list_recent, db_projects_upsert, db_reset_application_data, db_sessions_get,
        db_sessions_list, db_sessions_list_interrupted, db_sessions_upsert, db_settings_list, db_settings_set,
        db_steps_list, db_steps_upsert, db_tasks_list, db_tasks_upsert, db_tool_calls_list, db_tool_calls_upsert,
        db_usage_insert, db_usage_list, db_event_traces_append, db_event_traces_list,
        db_ai_change_sets_get, db_ai_change_sets_list_open, db_ai_change_sets_save, db_ai_review_decisions_insert,
        db_knowledge_proposals_get, db_knowledge_proposals_list, db_knowledge_proposals_list_conversation,
        db_knowledge_proposals_upsert,
    },
    github::{
        account_current, account_mark_onboarded, account_upsert, github_create_issue, github_create_pull,
        github_create_release, github_create_repository, github_current_user, github_get_repository,
        github_is_authenticated, github_list_issues, github_list_pulls, github_list_releases,
        github_list_repositories, github_sign_in, github_sign_out,
    },
    mcp::{
        mcp_bootstrap, mcp_call_tool, mcp_cancel, mcp_detect_blender, mcp_enable, mcp_get_prompt, mcp_health, mcp_list,
        mcp_list_prompts, mcp_list_resources, mcp_list_tools, mcp_probe_tcp, mcp_read_resource, mcp_record_usage,
        mcp_remove, mcp_restart, mcp_set_tool_enabled, mcp_start, mcp_stop, mcp_switch_project, mcp_upsert, mcp_which,
    },
    process::{process_execute, process_kill, process_run, process_start},
    project::{
        project_create_directory, project_create_file, project_create_folder, project_delete, project_detect_type,
        project_git_add, project_git_add_paths, project_git_add_remote, project_git_apply_patch,
        project_git_branch_details, project_git_branch_list, project_git_checkout, project_git_cherry_pick,
        project_git_clone, project_git_commit, project_git_commit_detail, project_git_compare,
        project_git_create_branch, project_git_delete_branch, project_git_diff, project_git_diff_at,
        project_git_discard_paths, project_git_drop_commit, project_git_fetch, project_git_file_contents, project_git_has_commits,
        project_git_init, project_git_is_repo, project_git_last_fetch, project_git_log, project_git_merge,
        project_git_merge_abort, project_git_merge_continue, project_git_pull, project_git_push, project_git_rebase, project_git_remotes, project_git_reset,
        project_git_restore_paths, project_git_revert, project_git_show_path, project_git_stash_create,
        project_git_status, project_git_unstage_paths, project_list, project_list_files, project_list_recent,
        project_open, project_read_bytes, project_read_file, project_remove, project_rename, project_reveal,
        project_search_files, project_walk_files, project_write_file,
    },
    rag::{rag_emit_progress, rag_mark_file_indexed, rag_plan_index, rag_remove_file, rag_search, rag_upsert_chunks},
    secrets::{secret_delete, secret_get, secret_set},
    system::{
        get_app_info, skill_pack_read, user_data_create, user_data_delete, user_data_list, user_data_read, user_data_walk,
        user_data_watch_specs, user_data_write,
    },
    terminal::{terminal_create, terminal_kill, terminal_resize, terminal_write},
};
use rag::store::LanceStore;
use state::AppState;
use tauri::Manager;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    #[cfg(debug_assertions)]
    {
        let manifest_env = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../.env");
        let _ = dotenvy::from_path(&manifest_env);
        let _ = dotenvy::from_filename(".env");
        let _ = dotenvy::from_filename("../.env");
    }

    tauri::Builder::default()
        .plugin(tauri_plugin_http::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_shell::init())
        .setup(|app| {
            let db = database::Database::open(app.handle())
                .map_err(|error| -> Box<dyn std::error::Error> { Box::new(error) })?;
            let vector = LanceStore::open(&db.data_dir)
                .map_err(|error| -> Box<dyn std::error::Error> { Box::new(error) })?;
            app.manage(AppState::new(db, vector));
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            get_app_info,
            skill_pack_read,
            user_data_list,
            user_data_walk,
            user_data_read,
            user_data_write,
            user_data_create,
            user_data_delete,
            user_data_watch_specs,
            project_open,
            project_list_recent,
            project_list,
            project_remove,
            project_create_folder,
            project_list_files,
            project_read_file,
            project_write_file,
            project_create_file,
            project_create_directory,
            project_rename,
            project_delete,
            project_reveal,
            project_detect_type,
            project_git_status,
            project_git_diff,
            project_git_diff_at,
            project_git_file_contents,
            project_git_is_repo,
            project_git_stash_create,
            project_git_show_path,
            project_git_restore_paths,
            project_git_remotes,
            project_git_init,
            project_git_add_remote,
            project_git_add,
            project_git_add_paths,
            project_git_unstage_paths,
            project_git_discard_paths,
            project_git_apply_patch,
            project_git_commit,
            project_git_push,
            project_git_pull,
            project_git_fetch,
            project_git_branch_list,
            project_git_branch_details,
            project_git_checkout,
            project_git_create_branch,
            project_git_delete_branch,
            project_git_merge,
            project_git_merge_continue,
            project_git_merge_abort,
            project_git_rebase,
            project_git_cherry_pick,
            project_git_revert,
            project_git_reset,
            project_git_drop_commit,
            project_git_log,
            project_git_commit_detail,
            project_git_compare,
            project_git_last_fetch,
            project_git_has_commits,
            project_git_clone,
            project_search_files,
            project_walk_files,
            project_read_bytes,
            process_execute,
            process_run,
            process_start,
            process_kill,
            terminal_create,
            terminal_write,
            terminal_resize,
            terminal_kill,
            agent_ping,
            secret_get,
            secret_set,
            secret_delete,
            github_sign_in,
            github_sign_out,
            github_current_user,
            github_is_authenticated,
            github_list_repositories,
            github_get_repository,
            github_create_repository,
            github_list_issues,
            github_create_issue,
            github_list_pulls,
            github_create_pull,
            github_list_releases,
            github_create_release,
            account_current,
            account_upsert,
            account_mark_onboarded,
            mcp_list,
            mcp_upsert,
            mcp_remove,
            mcp_enable,
            mcp_start,
            mcp_stop,
            mcp_restart,
            mcp_call_tool,
            mcp_list_tools,
            mcp_list_resources,
            mcp_list_prompts,
            mcp_read_resource,
            mcp_get_prompt,
            mcp_health,
            mcp_bootstrap,
            mcp_switch_project,
            mcp_record_usage,
            mcp_cancel,
            mcp_set_tool_enabled,
            mcp_which,
            mcp_detect_blender,
            mcp_probe_tcp,
            db_settings_list,
            db_settings_set,
            db_global_settings_list,
            db_global_settings_set,
            db_project_settings_list,
            db_project_settings_set,
            db_projects_upsert,
            db_projects_list_recent,
            db_projects_list,
            db_projects_get,
            db_projects_get_by_path,
            db_projects_delete,
            db_github_account_get,
            db_project_github_get,
            db_project_github_upsert,
            db_project_github_delete,
            db_conversations_upsert,
            db_conversations_list,
            db_conversations_get,
            db_conversations_archive,
            db_messages_upsert,
            db_messages_list,
            db_agent_runs_upsert,
            db_agent_runs_get,
            db_agent_runs_list,
            db_sessions_upsert,
            db_sessions_get,
            db_sessions_list,
            db_sessions_list_interrupted,
            db_tasks_upsert,
            db_tasks_list,
            db_tool_calls_upsert,
            db_tool_calls_list,
            db_steps_upsert,
            db_steps_list,
            db_event_traces_append,
            db_event_traces_list,
            db_agents_list,
            db_agents_upsert,
            db_memory_upsert,
            db_memory_get,
            db_memory_search,
            db_memory_delete,
            db_project_files_upsert,
            db_project_files_list,
            db_project_files_delete,
            db_usage_insert,
            db_usage_list,
            db_reset_application_data,
            db_export_application_data,
            db_import_application_data,
            db_ai_change_sets_save,
            db_ai_change_sets_get,
            db_ai_change_sets_list_open,
            db_ai_review_decisions_insert,
            db_knowledge_proposals_upsert,
            db_knowledge_proposals_get,
            db_knowledge_proposals_list,
            db_knowledge_proposals_list_conversation,
            rag_plan_index,
            rag_upsert_chunks,
            rag_mark_file_indexed,
            rag_remove_file,
            rag_search,
            rag_emit_progress,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
